"""drop question id unique key

Revision ID: 04b337c43fa2
Revises: 6e07a4c21f21
Create Date: 2022-10-08 17:18:08.900234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04b337c43fa2"
down_revision = "6e07a4c21f21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_game_questions_question_id", table_name="game_questions")
    op.create_index(
        op.f("ix_game_questions_question_id"),
        "game_questions",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_questions_question_id"), table_name="game_questions")
    op.create_index(
        "ix_game_questions_question_id", "game_questions", ["question_id"], unique=True
    )
    # ### end Alembic commands ###
