"""remove as uuid

Revision ID: 4248ae61b0ff
Revises: 889527573ef0
Create Date: 2022-10-06 12:24:57.919741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4248ae61b0ff"
down_revision = "889527573ef0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
