"""add offset column

Revision ID: 596cce348d82
Revises: feaee1dfd60d
Create Date: 2022-10-06 23:11:52.398800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "596cce348d82"
down_revision = "feaee1dfd60d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_quizzes", sa.Column("offset", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_quizzes", "offset")
    # ### end Alembic commands ###
