"""add quiz deleted column

Revision ID: 68fad4848e6d
Revises: f18d38652d10
Create Date: 2022-10-07 17:18:33.606972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68fad4848e6d"
down_revision = "f18d38652d10"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quizzes", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_quizzes_deleted"), "quizzes", ["deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quizzes_deleted"), table_name="quizzes")
    op.drop_column("quizzes", "deleted")
    # ### end Alembic commands ###
