"""rename game tables

Revision ID: 8e62dc7a01da
Revises: 596cce348d82
Create Date: 2022-10-06 23:33:29.443692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8e62dc7a01da"
down_revision = "596cce348d82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("started", sa.Boolean(), nullable=True),
        sa.Column("finished", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("offset", sa.Integer(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("quiz_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_questions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("answered", sa.Boolean(), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=True),
        sa.Column("game_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_answers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("choice", sa.String(), nullable=True),
        sa.Column("users_question_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["users_question_id"],
            ["game_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users_answers")
    op.drop_table("users_questions")
    op.drop_table("users_quizzes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_quizzes",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("started", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("finished", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("quiz_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("offset", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quizzes.id"], name="users_quizzes_quiz_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="users_quizzes_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="users_quizzes_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "users_answers",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("choice", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "users_question_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["users_question_id"],
            ["users_questions.id"],
            name="users_answers_users_question_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="users_answers_pkey"),
    )
    op.create_table(
        "users_questions",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("answered", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("skipped", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "users_quiz_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["users_quiz_id"],
            ["users_quizzes.id"],
            name="users_questions_users_quiz_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="users_questions_pkey"),
    )
    op.drop_table("game_answers")
    op.drop_table("game_questions")
    op.drop_table("games")
    # ### end Alembic commands ###
