"""remove order id

Revision ID: b42165ae945b
Revises: bebea4ea26a6
Create Date: 2022-10-08 23:47:29.016485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b42165ae945b"
down_revision = "bebea4ea26a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "game_questions", "questions", ["question_id"], ["id"])
    op.drop_column("questions", "order_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "order_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('questions_order_id_seq'::regclass)"),
            autoincrement=True,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "game_questions", type_="foreignkey")
    # ### end Alembic commands ###
