"""change foreign key name

Revision ID: bc1deb38784b
Revises: 8e62dc7a01da
Create Date: 2022-10-07 00:56:58.727637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc1deb38784b"
down_revision = "8e62dc7a01da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_answers",
        sa.Column("game_question_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.drop_constraint(
        "game_answers_users_question_id_fkey", "game_answers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "game_answers", "game_questions", ["game_question_id"], ["id"]
    )
    op.drop_column("game_answers", "users_question_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_answers",
        sa.Column(
            "users_question_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "game_answers", type_="foreignkey")
    op.create_foreign_key(
        "game_answers_users_question_id_fkey",
        "game_answers",
        "game_questions",
        ["users_question_id"],
        ["id"],
    )
    op.drop_column("game_answers", "game_question_id")
    # ### end Alembic commands ###
