"""remove started field from game

Revision ID: bebea4ea26a6
Revises: c05b4cc176fd
Create Date: 2022-10-08 21:12:05.580457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bebea4ea26a6"
down_revision = "c05b4cc176fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "started")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games", sa.Column("started", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
