"""remove choice from answer model

Revision ID: c05b4cc176fd
Revises: 04b337c43fa2
Create Date: 2022-10-08 19:31:17.490200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c05b4cc176fd"
down_revision = "04b337c43fa2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers", "choice")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers", sa.Column("choice", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
