"""add index to username

Revision ID: dbf1a8f72108
Revises: 0061e536315e
Create Date: 2022-10-05 23:20:47.450750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbf1a8f72108"
down_revision = "0061e536315e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    # ### end Alembic commands ###
