"""add question id to game question

Revision ID: f18d38652d10
Revises: bc1deb38784b
Create Date: 2022-10-07 15:05:36.506698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f18d38652d10"
down_revision = "bc1deb38784b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_questions",
        sa.Column("question_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_index(
        op.f("ix_game_questions_question_id"),
        "game_questions",
        ["question_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_questions_question_id"), table_name="game_questions")
    op.drop_column("game_questions", "question_id")
    # ### end Alembic commands ###
