"""add game models

Revision ID: feaee1dfd60d
Revises: f26d7ff85201
Create Date: 2022-10-06 22:55:17.565026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "feaee1dfd60d"
down_revision = "f26d7ff85201"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_quizzes",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("started", sa.Boolean(), nullable=True),
        sa.Column("finished", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("quiz_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_questions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("answered", sa.Boolean(), nullable=True),
        sa.Column("skipped", sa.Boolean(), nullable=True),
        sa.Column("users_quiz_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["users_quiz_id"],
            ["users_quizzes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_answers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("choice", sa.String(), nullable=True),
        sa.Column("users_question_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["users_question_id"],
            ["users_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("answers", sa.Column("value", sa.String(), nullable=True))
    op.alter_column(
        "questions",
        "order_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("nextval('questions_order_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "order_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("nextval('questions_order_id_seq'::regclass)"),
    )
    op.drop_column("answers", "value")
    op.drop_table("users_answers")
    op.drop_table("users_questions")
    op.drop_table("users_quizzes")
    # ### end Alembic commands ###
